### ISSUE TITLE
Simple "add container ip" syntax produces arguments error

### ISSUE THREAD

**Issue by IlyaSemenov** [xlucas/docker-flatip#1]
The very first example from the documentation doesn't work:
```
root@farm:~# docker-flatip add 012abcd 192.168.1.10/24
ERROR : wrong number of arguments for command add.
Usage:
docker-flatip OPERATION CONTAINER [OPTIONS]
    OPERATION := { add, clean, del, list }
        add  : container ip [-i proto:{port|all},...] [-o proto:{port|all},...] [-h host_nic]
        clean
        del  : container ...
        list
```

This is because the script checks that `add` command has at least 4 arguments (although 3 is enough).

**Comment by xlucas** [comment]
Thanks for reporting this, that's indeed a mistake in the script.

**Comment by thatsk** [comment]
![screenshot from 2015-12-03 15-03-38](https://cloud.githubusercontent.com/assets/15324013/11556829/600fc9ba-99d1-11e5-9ae9-b920c375d596.png)

**Comment by thatsk** [comment]
I have issues to giving the static ip address to docker container ....IS this script correct or make this fix it !!!???

**Comment by xlucas** [comment]
Hi, firsteval: calm down.

Now, can you hit me up with the reason that led you trying to assign IP address "/bin/bash" to your container ? 

To fix this, comment the `set -e` line, run `docker-flatip del <container_id>` then uncomment `set -e ` and run the relevant `docker-flatip add` command.

**Comment by thatsk** [comment]
First of all Thanks For replying.
You are doing faboulus JOb.

If really docker images are access over the internet .
So we have to create staic ip for web containers that can access over the internet and ssh them .
And Also in production environment if we have developer want to use different OS. We can give them So in one environment We can large number of containers.
And use them With uniques ips.
So for that i want to use. 

See You soon with testing the script

**Comment by thatsk** [comment]
again Another Issues Is facing .
My machine configuration is as follows:
Host machine is Centos7 (192.168.1.200)
And in That docker installed
And container is ubuntu (172.72.0.1)
so i want to get ubuntu ip 192.168.1.8 or something)
So that can be ssh can get in the network through 192.168.1 series.
R u getting Buddy my point????
![screenshot from 2015-12-04 13-53-52](https://cloud.githubusercontent.com/assets/15324013/11585089/54d63296-9a8f-11e5-80b6-a9183c7fba51.png)

**Comment by thatsk** [comment]
I have tested .... finally not assigning ip
